### ISSUE TITLE
Bug: srt files with CRLF line endings don't load properly

### ISSUE THREAD

**Issue by judyfong** [gong-io/gecko#106]
### System information
- **Debian Stretch**
- **The srt files are produced in a Windows environment** 

### Describe the problem
I load an srt, rttm, and wav file.
When I load an srt file with CRLF line endings no segmentation information is shown.
However, when I change the line endings to LF all the information loads as usual,
The segment labelling section also becomes non interactive.
![](https://i.imgur.com/TuDsBks.png)
The first image shows what happens if I also upload an rttm file.

![](https://i.imgur.com/kZCcS7t.png)
This second image shows what happens if I only upload the crlf srt file and the wav file.

I don't think it's related to my operating system but I do believe it is related to the operating system that created the srt files.
### Source code / logs

You can use this vim command to convert your srt files to have crlf and recreate the issue:
` vim file.txt -c "set ff=dos" -c ":wq"`

**Comment by strelok2012** [comment]
Hi!

Sorry for a long answer, fixed in https://github.com/gong-io/gecko/pull/114
