### ISSUE TITLE
question about the segment dragging

### ISSUE THREAD

**Issue by songtaoshi** [gong-io/gecko#122]
Hi, Thanks for awesome project!

I am questioning about the **segment dragging**. It seems that the online demo segment dragging can only be dragged in the whole level while the youtube video can dragged for different length for top and down part. 

**This is for youtube video version:**
![image](https://user-images.githubusercontent.com/20240391/79183417-ff56ab00-7e43-11ea-9be1-2702e5eb53d4.png)

**This is for online demo version:**
![image](https://user-images.githubusercontent.com/20240391/79183477-2b722c00-7e44-11ea-8999-3f0c5573eac5.png)

**Comment by GolanLevy** [comment]
Hi @songtaoshi 

The "youtube" version is the same version as the demo, just when two annotation/transcript files are loaded. 

Try it yourself :)

**Comment by songtaoshi** [comment]
thx! so it's just the difference of two
