### ISSUE TITLE
Bug: Check regions error Overlapping in file: 

### ISSUE THREAD

**Issue by judyfong** [gong-io/gecko#123]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Debian
- **Python version**: 3

### Describe the problem
I use Gecko to create segments then save them as json, srt, and rttm files. However, if I want to reload the rttm or json file, I sometimes get overlap errors. This is despite not modifying the file at all after saving it from Gecko. The errors do not occur with srt files. The only timing difference between json/rttm and srt files is srt has a precision of 3 decimal places and json/rttm has a precision of 2 decimal places.

For example with the follow two srt segments:
```
 7
 00:01:35,635 --> 00:01:58,955
 <NA>
  
 8
 00:01:58,955 --> 00:02:00,436
 <NA>
```

and the corresponding rttm segments:

```
SPEAKER <NA> <NA> 95.64 23.32 <NA> <NA> 1 <NA> <NA>
SPEAKER <NA> <NA> 118.95 1.49 <NA> <NA> 2 <NA> <NA>
```

There is no overlap issue with the srt segments but there is a .01 overlap between the first and second rttm segments.

### Source code / logs
The problem is likely a rounding error. I believe the problem is created from changing the precision of the segment timing from 3 decimal places to 2 decimal places via toFixed(2).

Here is a toy solution with the segments given above:
```
  var start = 95.635;
  var s = start.toFixed(2); //95.64
  var end = 118.955;
  var e = end.toFixed(2); //118.95
  var gecko_diff = (end - start).toFixed(2); // 23.32
  var correct_diff = (end.toFixed(2) - start.toFixed(2)).toFixed(2); //23.31
```

By fixing the region boundary decimal places to the final rttm ones before subtracting, it guarantees there will not be an overlap issue when reloading the file into Gecko.

**Comment by GolanLevy** [comment]
Hi @judyfong,

Thanks for the fix, we will check it soon.
One thing I'm not sure about - you say this happens also for json files?
I did not see any fix for that in the PR.

Thanks,
Golan

**Comment by judyfong** [comment]
Yeah I did have problems with the json files sometimes, too. But I can't seem to recreate the problem for json files. So I might be mistaken.
