### ISSUE TITLE
Annotation formats

### ISSUE THREAD

**Issue by xeruf** [gong-io/gecko#145]
### Describe the problem

Hey, this tool seems really nice, but is there a specification for the annotation formats (e.g. JSON) it uses? Which fields and how they're supposed to be arranged?

I'm using a custom vosk script to get a transcription and have no idea how to get that into a compliant format for gecko :/

**Comment by GolanLevy** [comment]
Hi @xerus2000,
You can find examples of the json format in samples/demo.json.
Let me know if you have any more questions

**Comment by xerus2000** [comment]
Thanks, that is indeed helpful.
However, I am wondering about the "monologues" field - is there also a "dialogues" field? What does it mean?

**Comment by GolanLevy** [comment]
A monologue is just our terminology for a logical unit of several words. This is usually considered to be a contiguous talking of one speaker (like a sentence or more).
We do not have a dialogues field; you would probably want to consider a dialogue as several monologues with different speakers.
Hope it helps
