### ISSUE TITLE
How I make words clickable ,

### ISSUE THREAD

**Issue by wajidch** [gong-io/gecko#172]
Hi,
First of all your library is awesome. I appreciated your great effort keep it up.

I have one requirement I want to click on complete sentence and want to perform some functionality 

and also is this possible to split the text in a different sentence in a new line 
like below

Hello how are you
Hi I am fine

I am waiting for your response kindly reply me

**Comment by rotem-1996** [comment]
Hi @wajidch,
Thank you so much.

I'm sorry but we are not planning on having a special functionality per sentence.

It is possible to split the text into two segments by hitting Shift+Enter, however only in proofreading view.

Hope that helps,
Rotem
