### ISSUE TITLE
Multiple Records Annotations

### ISSUE THREAD

**Issue by tomerghelber** [gong-io/gecko#173]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: All
- **Python version**: All

### Describe the problem
We have separated records of each side in a conversation. We want to annotate them all together and if possible relate the annotations to the batch or to one steam (this part is not very important).

0. Annotating in separation loses a lot of annotation and context so we want to annotate all of them together.
1. Merging voice to one stream is easy, but with video, it starts to be dirty.
2. Separated streams (not merging them) can give a better context, clear background noise from one side or when they talk to each other.

### Source code / logs
It is a feature request so I don't have any logs/source code to show.

**Comment by rotem-1996** [comment]
Hi @tomerghelber
First thank you for using our tool!
We do have this feature planned for the future, however it is not yet in the works.
If it's urgent you are welcome to submit a pull request and we will review it.

Thanks
Rotem

**Comment by tomerghelber** [comment]
Ok, is there another issue or I can start here?

**Comment by rotem-1996** [comment]
You can start here :)
