### ISSUE TITLE
How clear editable-words filed 

### ISSUE THREAD

**Issue by wajidch** [gong-io/gecko#175]
Hi,
Can you please tell me how to clear editable-words filed
i want to clear this 
   <editable-words
                        id="editableId"
                       
                            region="ctrl.currentRegions[$index]"
                            file-index="$index"
                            class="editable-words"
                            control="ctrl"
                        >
                        </editable-words>
Waiting for your response please let me know

**Comment by rotem-1996** [comment]
Hi @wajidch,
I'm sorry I'm not sure I understand what you want, so just to clarify you would like to remove the "editable-words" element from gecko?
