### ISSUE TITLE
Running Gecko locally without internet connection (data privacy)

### ISSUE THREAD

**Issue by choward232** [gong-io/gecko#176]
Hello Gecko team,

I'm interested in using your platform to annotate my audio data, but due to data privacy concerns, I need to run the application without access to the internet. Is this something that is possible? Whenever I try to run the app locally without internet, I have trouble accessing the GUI. 

More broadly, I want to make sure that none of the data that I annotate is saved to any external server off of the local machine that runs the program. Some insight into the privacy of annotated data here when the S3 bucket isn't configured would be extremely helpful.

Thanks!

**Comment by rotem-1996** [comment]
Hey @choward232,

If I understand correctly you are trying to build and run Gecko without internet, and unfortunately that is not possible. However, to answer your second question, Gecko does not save anything (except for locally in the browser's local storage) if you don't connect it to an s3 bucket, therefore, if you prefer, you could build and run it locally with internet connection.
Though, I am not sure how github handles the data used within its builds, so I think this is the best approach.
