### ISSUE TITLE
Concatenation of consecutive words may not be saved

### ISSUE THREAD

**Issue by owen1512** [gong-io/gecko#189]
Hi

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: your demo platform https://gong-io.github.io/gecko/
- **Python version**: your demo platform https://gong-io.github.io/gecko/

### Describe the problem
Concatenation of consecutive words may not be saved when clicking on "play", "play region" or somewhere else on the waveform.
You can reproduce this issue trying to remove the first white-space of the first region of the demo file (between "Hi," and "Virgil").
You may have to try a few time to reproduce this issue, but on my side, it happens most of the time whatever the method used to suppress this white-space.

### Source code / logs
NA

**Comment by rotem-1996** [comment]
Hey,
We recently fixed a similar problem, could you check if it's still an active issue?
Thank you very much for your feedback
