### ISSUE TITLE
Doc request: where do you convert monologues object to wavesurfer regions ? 

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#35]
Hi,
I'd like to add some fields to the current json format, e.g. model confidence in the id of a speaker.
After writing a toy file with speaker looking like this:
```json
"speaker" : {
      "id" : "Virgil",
      "confidence":0.8
    }
```
It gets correctly parsed to a monologue using `app/textFormats/json.js` `parse` function but I'm not sure where it gets converted into a wavesurfer region ?

**Comment by PaulLerner** [comment]
On a related topic : I'd like that the user would not be able to resize and create new segments, so I added `resize:false`, in the options of the [addRegion function](https://github.com/gong-io/gecko/blob/master/app/controller.js#L1057).
However, after applying this it looks like the regions won't load and I get an error:
```js
TypeError: elem.children[0] is undefined
```
which relates to this line : https://github.com/gong-io/gecko/blob/master/app/controller.js#L363

**Comment by strelok2012** [comment]
> Hi,
> I'd like to add some fields to the current json format, e.g. model confidence in the id of a speaker.
> After writing a toy file with speaker looking like this:
> 
> ```json
> "speaker" : {
>       "id" : "Virgil",
>       "confidence":0.8
>     }
> ```
> 
> It gets correctly parsed to a monologue using `app/textFormats/json.js` `parse` function but I'm not sure where it gets converted into a wavesurfer region ?

Hi Paul

Yes, parsing/converting is going on in `textFormats/json.js` file

Later this parsed data converts to wavesurfer regions [here](https://github.com/gong-io/gecko/blob/master/app/controller.js#L1025)

**Comment by PaulLerner** [comment]
Ok, thank you.
Do you have any idea about the resize problem ?

> On a related topic : I'd like that the user would not be able to resize and create new segments, so I added `resize:false`, in the options of the [addRegion function](https://github.com/gong-io/gecko/blob/master/app/controller.js#L1057).
> However, after applying this it looks like the regions won't load and I get an error:
> 
> ```js
> TypeError: elem.children[0] is undefined
> ```
> 
> which relates to this line : https://github.com/gong-io/gecko/blob/master/app/controller.js#L363

**Comment by strelok2012** [comment]
Hi Paul, sorry for long answer

Just wrap [this line](https://github.com/gong-io/gecko/blob/master/app/controller.js#L363) to

```
// unset handlers manual style
 if (elem.children.length) {
    elem.children[0].removeAttribute('style');
    elem.children[1].removeAttribute('style');
}
```

There is needed because with resize:false regions doesn't has a resize handles, so elem.children in an empty

**Comment by PaulLerner** [comment]
No problem, thank you !
