### ISSUE TITLE
Question: why do you save speaker color in json ?

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#38]
Hi,
I don't understand why do you [save speaker color in json](https://github.com/gong-io/gecko/blob/master/app/textFormats/json.js#L93) but you don't [load it](https://github.com/gong-io/gecko/blob/master/app/controller.js#L1057).

Would you like to implement the loading later ?

**Comment by GolanLevy** [comment]
Hey Paul,

The loading does work (I've just checked).
Just to make sure we are talking on the same thing, here is what I tried:
Load demo>change one of the colors of the speaker>save>load the demo audio with the downloaded file> see that the color is similar to the saved color.

Note that the colors are handled outside the regions' plugin and are being initialized [here](https://github.com/gong-io/gecko/blob/master/app/controller.js#L991).
A region gets its color [here](https://github.com/gong-io/gecko/blob/master/app/controller.js#L639)
The colors are saved under each of the 'speaker' entries in the json file and so they are being loaded from it.
The appropriate thing to do is to put it in some kind of metadata object, parallel to the 'monologues' entry, so we won't have so many duplicates.

It will be great if you will make this separation.
Please consider two issues: 
1) backwards compatibility (unless you think it is unnecessary and then I will consider it with my team)
2) synchronizing colors between the same speaker in different files.

**Comment by PaulLerner** [comment]
Hi Golan,
Thank you for your answer, sorry about that, I'm not sure why I thought that color loading was not efficient.
Thanks for the info !
