### ISSUE TITLE
Feature request: trigger REST API calls from Gecko every time the user interacts with it

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#59]
Hi,

As discussed with @omriallouche and @hbredin, we'd like that every time that the users interacts with Gecko (e.g. when a new annotation is created, when an existing one is updated), a REST API call is triggered.

Bests,

**Comment by omriallouche** [comment]
It seems useful to fire events that listeners can listen to when the user makes an edit.
This way, the listeners can ping some remote URL or do whatever you want.
Vitaliy, can you add code triggering edit events? 
Paul can then take care of the REST API calls by listening to these.

**Comment by GolanLevy** [comment]
Hi @PaulLerner,

PR https://github.com/gong-io/gecko/pull/61 was merged into master.
Please tell us if it is what you wished for.

Thanks

**Comment by GolanLevy** [comment]
Closed due to inactivity.
