### ISSUE TITLE
Feature/doc request: display video and audio waveform at the same level

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#60]
Hi, 
I already discussed about that with @GolanLevy :
We noticed that the video player in gecko isn't much ergonomic : since it's above the waveform/timeline, on a classic 16:9 screen it's hard to seen neither the segment labelling nor the transcription section.

We thought it would be better to have both video and audio waveform at the same level, left and right like this :
![gecko video](https://user-images.githubusercontent.com/25532159/70344004-eff1a080-1858-11ea-8cb4-fbe67ebe1dcc.png)

I did it [on my fork](https://github.com/PaulLerner/gecko/tree/refactor/video_display) but it broke the clicking on the waveform, can you explain where that happens / any hints to fix it ?

Bests,

**Comment by strelok2012** [comment]
Hi Paul

I catched this bug but for now i cannot said you anything - need more time to research, will do it soon.

**Comment by PaulLerner** [comment]
Hi @strelok2012 , I noticed that this is not caused by my fork, this also happens on the master and online version :
The waveform gets all white like this :
![image](https://user-images.githubusercontent.com/25532159/70815825-83cdea00-1dce-11ea-9af5-adea1b339c16.png)

And the audio is not sync with the video.

Bests,

**Comment by PaulLerner** [comment]
Opened #66, closing this because I think the video issues are unrelated to this feature request
