### ISSUE TITLE
Fix: video player

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#66]
Hi,

I already opened issue #60 which is related but I think it's better to have a clean issue here (I'll close #60).
I noticed several bugs :
- Clicking on the waveform is ineffective
- It gets all white like this :
![image](https://user-images.githubusercontent.com/25532159/70815825-83cdea00-1dce-11ea-9af5-adea1b339c16.png)
- Sometime the regions doesn't display at all, although this happens only on one of my two machines (both have ubuntu 16.04 and run gecko in firefox) :
  * doesn't happen on my laptop witch has :
    - npm 6.12.0
    - node v12.13.0
  * happens on my work computer which has:
     - npm 6.11.3 
     - node v12.11.1
- Can't jump regions in video mode, I fixed it here : https://github.com/PaulLerner/gecko/tree/fix/video (Should I PR ?). 
- Can't playregion in video mode, I wasn't able to solve it with the same trick as my fix/video. The player gets stuck in the same frame and audio and video get out of sync

Have a good week-end,

**Comment by strelok2012** [comment]
Hi Paul, thanks

Working on it

**Comment by GolanLevy** [comment]
The bugs were fixed.
In the future we will change the video display to a more comfortable component

**Comment by PaulLerner** [comment]
Cool, thanks !
