### ISSUE TITLE
Fix: Proofreading-view

### ISSUE THREAD

**Issue by PaulLerner** [gong-io/gecko#76]
Hi,

### Describe the problem
The proof-reading view gets buggy when one deletes a region. See my screenshot :

![gecko bug proofreading](https://user-images.githubusercontent.com/25532159/71478321-45352800-27ef-11ea-9880-f3be7b15ce12.png)

### Source code / logs
No error messages in the console

### How to reproduce
- launch gecko (e.g. from online version https://gong-io.github.io/gecko/)
- load demo
- toggle proofreading view
- delete any region

Merry Christmas :)

**Comment by GolanLevy** [comment]
Thank you,
we are on it.

Happy Hanukkah!

**Comment by GolanLevy** [comment]
Hi Paul,
It seems to be okay now.
Let me know if you find any problem.
If you don't, please close.

**Comment by PaulLerner** [comment]
Hi Golan,
Yeah it works fine thanks :) (I though you'd close this issue a long time ago)
